module.exports = {
  abs: require('./abs'),
  acos: require('./acos'),
  add: require('./add'),
  asin: require('./asin'),
  atan: require('./atan'),
  atan2: require('./atan2'),
  ceil: require('./ceil'),
  cos: require('./cos'),
  degreesToRadians: require('./degreesToRadians'),
  divide: require('./divide'),
  exp: require('./exp'),
  floor: require('./floor'),
  log: require('./log'),
  max: require('./max'),
  min: require('./min'),
  multiply: require('./multiply'),
  pow: require('./pow'),
  radiansToDegrees: require('./radiansToDegrees'),
  random: require('./random'),
  round: require('./round'),
  sqrt: require('./sqrt'),
  substract: require('./substract'),
  tan: require('./tan')
}